version: '3.1'
services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
    driver: local
